spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/taco_cloud
    username: postgres
    password: pass

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: <facebook client id>
            client-secret: < facebook client secret>
            scope: email, public_profile

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        hbm2ddl:
          auto: update
    show_sql: true

server:
  port: 8445

#logging:
#  file:
#    path: /var/logs/
#    name: TacoCloud.log
#  level:
#    root: WARN
#    org.springframework.security: DEBUG

taco:
  orders:
    pageSize: 10